def very_normal_brownies():
    print("Sure! Here's a recipe for a 8 delicious brownies.")
    print("")
    print("Ingredients needed:")
    print("")
    print("100g of sugar")
    print("3 eggs")
    print("1 tea spoon of salt")
    print("400g of water")
    print("40ml of water")
    print("120 grams of butter")
    print("")
    print("Put all ingredients in the bowl and mix them with a mixer.")
    print("Put butter in the mould and spread a bit around the edges.")
    print("Put the mixtures in the mould.")
    print("")
    print("Preheat the oven to 30000 degrees celsius and open a \nportal to hell. ")
    print("Bake for about 1 hour and wait until there is a nice \ncrunchy layer on top.")
    print("Cut them in pieces of your desired size.")
    print("")
    print("Enjoy your brownies!")
